import openai
import random
import json
openai.api_key = "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"
prompt = """
Task: Sequence video verification
Dataset: CSV
**Prompt**  

I want you to act as a professional annotator. You need to generate the question-and-answer pair data to train the model based on the provided data. I will give you the image sampled from the video or the image caption or video summary of this video and the original labels. All the information that the answer needs is contained in the label files. Please remember you are a professional annotator and finish your work as required. Do not consider to briefly generate your output.

There are some rules you need to obey:  

1) For generating questions based on the provided image:

- Basic setting: The generated question should showcase this information: you are provided a video about something and need try to understand what happened this video.

- Question Type: It could be a judgment question, essay question, or any other specified format.
  - If you want to create judgement question. Please ensure the response is No or Yes with the same probability.  Note that the probability of each response, i.e. Yes's and No's, should be equal and balanced, so ensure a balance in question devising.
- Contextual Background: Craft a background story that provides a context to the scene depicted in the image. This might involve describing the setting, the time, the atmosphere, or any relevant details that set the stage.

- Motivation: Explain the motivation or reason behind the question. For instance, begin with an introduction explaining the scenario or situation, then delve into why this particular question is being asked. Further, indicate what one hopes to achieve or understand by getting the answer.

- Activity Description: Describe the activities or events taking place in the video, but avoid direct mentions of the exact action being performed.

- Variety in Storytelling: Ensure a diverse range of background stories. Repeating the same story or context should be avoided.

- Diversity in Format: The generated questions and answers should come in a variety of formats and narratives to cater to different interpretations of the video.


2) For generating answer:
Based on the annotation, video and original answer:
- First of all, you need to generate the standard original answer based on the annotations of this video for the original question.
- Following the generated question by you, you need to write many details. Examine the provided image carefully based on the supplied photograph or image caption. Describe the scene in great detail, focusing on the primary action. 
- Additionally, elaborate on the potential context or background story that could explain the circumstances leading up to this moment.
     
3) the generated results:
- Ensure Variety: While maintaining continuity, make sure each pair is unique and captures different aspects of the source materials.
- Maintain Clarity: Despite the number of pairs, each question and answer should be clear, concise, and relevant to the source materials.


4) the output format:

- First of all, please use JSON format to reply to me.
- Please follow this format to give the final result. Generate 10 continuous question-answer pairs based on the video annotations, images, and associated captions or video summaries. Do not include any interjected notes, disclaimers, or extraneous information. Simply produce the pairs consecutively. Do not pause, add notes, disclaimers, or any other commentary. Just provide 10 uninterrupted Q&A pairs.

    ```json
    {
        "1":{
            "Original question": "This is the question provided by me or generated by you",
            "Original answer": "This is the answer you created based on the annotation and the original question",
            "The question with details": "Your generated question, elaborated in depth, which should adhere to the requirements and incorporate more narrative or motivation elements",
            "The answer with details": "Your answer, expanded and detailed, elaborated in depth, which should offer a comprehensive understanding by explaining the context, reasons, scene knowledge, action motivations, or other pertinent information.",
        },
        "2":{},
        ...
        "10":{},
    }

    ```
    Now I am providing you with specific details about the qa pair you need to generate.
    
    - Question 1.1: 
    - Original question: What are the actions in the sequence video and in what order?
    - Original simple answer: As shown in JSON, it is the annotations of this video, that describe the action occurring sequence.
"""
# with open('label_bank.json', 'r') as json_file:

# print(final_output)

label = """ "4.2":[
    "take up the test tube",
    "take up the horn tube",
    "insert the horn tube",
    "screw the iron clamp",
    "take up the conical flask",
    "pour the conical flask",
    "put down the conical flask",
]
"""
def csv_annotation(label):
    messages = [
        {"role": "system", "content": prompt},
        {"role": "user", "content": label}
    ]

    res = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages
    )

    return res["choices"][0]["message"]["content"]
generated_content = csv_annotation(label)